// ignore_for_file: unnecessary_this, unnecessary_new, prefer_collection_literals

class CategoryTicket {
  int? request;
  int? incident;

  CategoryTicket({this.request, this.incident});

  CategoryTicket.fromJson(Map<String, dynamic> json) {
    request = json['request'];
    incident = json['incident'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['request'] = this.request;
    data['incident'] = this.incident;
    return data;
  }
}

class TechGroupTicket {
  int? request;
  int? incident;

  TechGroupTicket({this.request, this.incident});

  TechGroupTicket.fromJson(Map<String, dynamic> json) {
    request = json['request'];
    incident = json['incident'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['request'] = this.request;
    data['incident'] = this.incident;
    return data;
  }
}

class StatusTicket {
  int? request;
  int? incident;

  StatusTicket({this.request, this.incident});

  StatusTicket.fromJson(Map<String, dynamic> json) {
    request = json['request'];
    incident = json['incident'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['request'] = this.request;
    data['incident'] = this.incident;
    return data;
  }
}

class RequestLists {
  int? id;
  String? format;
  String? subject;
  String? status;
  String? techGroup;
  String? technician;
  String? createDate;
  String? dueDate;
  String? type;
  int? createDateLong;
  int? dueDateLong;
  String? requester;

  RequestLists(
      {this.id,
      this.format,
      this.subject,
      this.status,
      this.techGroup,
      this.technician,
      this.createDate,
      this.dueDate,
      this.type,
      this.createDateLong,
      this.dueDateLong,
      this.requester});

  RequestLists.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    format = json['format'];
    subject = json['subject'];
    status = json['status'];
    techGroup = json['techGroup'];
    technician = json['technician'];
    createDate = json['createDate'];
    dueDate = json['dueDate'];
    type = json['type'];
    createDateLong = json['createDateLong'];
    dueDateLong = json['dueDateLong'];
    requester = json['requester'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['format'] = this.format;
    data['subject'] = this.subject;
    data['status'] = this.status;
    data['techGroup'] = this.techGroup;
    data['technician'] = this.technician;
    data['createDate'] = this.createDate;
    data['dueDate'] = this.dueDate;
    data['type'] = this.type;
    data['createDateLong'] = this.createDateLong;
    data['dueDateLong'] = this.dueDateLong;
    data['requester'] = this.requester;
    return data;
  }
}

class Autogenerated {
  int? request;
  int? incident;

  Autogenerated({this.request, this.incident});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    request = json['request'];
    incident = json['incident'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['request'] = this.request;
    data['incident'] = this.incident;
    return data;
  }
}
